#!/bin/env bash

set -ue

GIT_REPO=$(dirname "$(readlink -f "$0")")
BACKUP_FOLDER=$GIT_REPO/backups
FILE_LIST="vimrc emacs.d"

mkdir -p "$BACKUP_FOLDER"
for FILE in $FILE_LIST
do
  if [ -e "$HOME/.$FILE" ]
  then
    echo "Moving $FILE to $BACKUP_FOLDER"
    mv "$HOME/.$FILE" "$BACKUP_FOLDER"
  fi
  echo "Link $FILE to home directory"
  ln -s "$GIT_REPO/$FILE" "$HOME/.$FILE"
done
